import os

SESSION_COOKIE_NAME = "ROOMBOOK_SESSION"
SESSION_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365  # 1 year
SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_SAMESITE = "lax"
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "false").lower() == "true"
SESSION_SIGNING_SECRET = os.getenv("SESSION_SIGNING_SECRET", "change-this-in-production")
